### ISSUE TITLE
New core config repo nodejs/eslint-plugin-nodejs-internal

### ISSUE THREAD

**Issue by nschonni** [iansu/eslint-plugin-node-core#1]
I realized after getting https://github.com/nodejs/eslint-plugin-nodejs-internal that it might overlap with what you have here, since this package looks like it's referenced by the core rules

**Comment by iansu** [comment]
This package isn't directly used by Node.js. It's a copy of the plugin found here: https://github.com/nodejs/node/blob/master/tools/node_modules/eslint-plugin-node-core/index.js

The intention of this package to use that plugin outside of Node core. At the moment it's being used here: https://github.com/pkgjs/parseargs
